---

- name: Import testing-privesc
  ansible.builtin.import_tasks: testing-privesc.yml
  when: harden_darwin_testing_privesc

- name: Import testing-speculative
  ansible.builtin.import_tasks: testing-speculative.yml
  when:
    - harden_darwin_testing_speculative
    - ansible_facts['architecture'] == 'i386' or ansible_facts['architecture'] == 'x86_64'
